### ISSUE TITLE
Can't build with GCC 4.3 and 4.5

### ISSUE THREAD

**Issue by Zenitur** [simleb/clinfo#4]
With 4.8 it builds fine. https://build.opensuse.org/package/show/home:linux4humans:wine-staging/clinfo

```
cc -fomit-frame-pointer -fmessage-length=0 -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -std=c99 -g -Wall -Wextra -pedantic -Werror   -c -o clinfo.o src/clinfo.c
cc1: warnings being treated as errors
src/clinfo.c: In function 'oclIcdProps':
src/clinfo.c:2689:2: error: dereferencing type-punned pointer will break strict-aliasing rules
make: *** [clinfo.o] Error 1
```

**Comment by simleb** [comment]
Unless I am mistaken, the error doesn't seem to be in my code (there is no `oclIcdProps` function and much less than 2689 lines).

**Comment by Oblomov** [comment]
Hm I think this is an issue with my clinfo. @Zenitur, can you close the bug here and reopen it for Oblomov/clinfo?

**Comment by Zenitur** [comment]
@Oblomov, oh, there are different applications. Okayю
